SHAPES = {
    "AA" : "aa",
    "AE" : "aa",
    "AH" : "ah",
    "AO" : "oh",
    "AW" : "ah",
    "AY" : "ah",
    "B" : "mbp",
    "CH" : "zhj",
    "D" : "sczshch",
    "DH" : "lth",
    "EH" : "aa",
    "ER" : "er",
    "EY" : "aa",
    "F" : "fv",
    "G" : "ah",
    "HH" : "h",
    "IH" : "i",
    "IY" : "i",
    "JH" : "zhj",
    "K" : "k",
    "L" : "lth",
    "M" : "mbp",
    "N" : "en",
    "NG" : "k",
    "OW" : "oh",
    "OY" : "oh",
    "P" : "mbp",
    "R" : "oh",
    "S" : "sczshch",
    "SH": "zhj",
    "T" : "h",
    "TH" : "lth",
    "UH": "eeuh",
    "UW" : "i",
    "V" : "fv",
    "W" : "oou",
    "Y" : "eeuh",
    "ZH" : "zhj",
    "Z": "sczshch",
}
