SHAPES = {
    "AA" : "i",
    "AE" : "i",
    "AH" : "ah",
    "AO" : "i",
    "AW" : "ah",
    "AY" : "ah",
    "B" : "mbp",
    "CH" : "k",
    "D" : "ee",
    "DH" : "lth",
    "EH" : "ah",
    "ER" : "i",
    "EY" : "ah",
    "F" : "fv",
    "G" : "ee",
    "HH" : "enwh",
    "IH" : "i",
    "IY" : "i",
    "JH" : "sczshch",
    "K" : "ee",
    "L" : "lth",
    "M" : "mbp",
    "N" : "k",
    "NG" : "k",
    "OW" : "oh",
    "OY" : "oh",
    "P" : "mbp",
    "R" : "oh",
    "S" : "k",
    "SH": "k",
    "T" : "ee",
    "TH" : "lth",
    "UH": "ah",
    "UW" : "ah",
    "V" : "fv",
    "W" : "wr",
    "Y" : "ee",
    "ZH" : "oh",
    "Z": "sczshch",
}
